PATH_TO_TRAIN_DATA: "./sample_data.pkl"
PATH_TO_VALIDATION_DATA: "./sample_data.pkl"

MODEL_CHECKPOINT: "facebook/bart-large"

SOURCE_DIALOG_MAX_LEN: 512
SOURCE_DIALOG_COLUMN: "dialog_history_proc"

ACTION_COUNT: 22 # modification 
ACTION_DIM: 1024
# TODO: to be updated, since the vocabulary for action indices is not properly formulated
ACTION_PADDING_IDX: 0 
ACTION_START_IDX: 1
SOURCE_ACTION_MAX_LEN: 300 
TARGET_ACTION_MAX_LEN: 512 
SOURCE_ACTION_COLUMN: "source_actions"
TARGET_ACTION_COLUMN: "target_actions"

VISUAL_DIM: 768 # when utilizing google/vit-base-patch16-224
SOURCE_VISUAL_MAX_LEN: 300 
TARGET_VISUAL_MAX_LEN: 512
SOURCE_VISUAL_COLUMN: "driver_images_history_feats"
TARGET_VISUAL_COLUMN: "driver_images_future_feats"

OBJECT_COUNT: 97
TARGET_OBJ_INTERACTION_ACTION_COLUMN: "target_obj_interaction_actions"
TARGET_OBJECT_COLUMN: "target_objects"

BATCH_SIZE: 2
MAX_EPOCHS: 50

BASE_LEARNING_RATE: 5e-6
NEW_LEARNING_RATE: 5e-5
WEIGHT_DECAY: 1e-4

NUM_DECODER_LAYERS: 6
DROPOUT: 0.2

RESULT_OUTPUT_DIR: "./results"
MODEL_SETTING: "multimodal" # `unimodal` or `multimodal`

# need to consider this in generation_utils.py
MAX_PRED_LEN: 80 

LOSS_WEIGHT_REGULARIZATION: 0.1