MODEL_CHECKPOINT: "facebook/bart-large"

SOURCE_DIALOG_MAX_LEN: 512
SOURCE_DIALOG_COLUMN: "dialog_history_proc"

ACTION_DIM: 128
SOURCE_ACTION_MAX_LEN: 150 
TARGET_ACTION_MAX_LEN: 50
SOURCE_ACTION_COLUMN: "source_actions"
TARGET_ACTION_COLUMN: "target_actions"

VISUAL_DIM: 768 # when utilizing google/vit-base-patch16-224
SOURCE_VISUAL_MAX_LEN: 150 
TARGET_VISUAL_MAX_LEN: 50
SOURCE_VISUAL_COLUMN: "driver_images_history_feats"
TARGET_VISUAL_COLUMN: "driver_images_future_feats"

BATCH_SIZE: 4
MAX_EPOCHS: 50

BASE_LEARNING_RATE: 5e-6
NEW_LEARNING_RATE: 5e-5
WEIGHT_DECAY: 1e-4